### ISSUE TITLE
Add Documentation for Getting Started with Maven & Eclipse

### ISSUE THREAD

**Issue by davidbuhler** [gwtbootstrap3/gwtbootstrap3#174]
It would be helpful to have a step-by-step guide to getting the project set-up and running with Maven and Eclipse.

**Comment by jgodi** [comment]
Anyone that uses Eclipse willing to write a wiki page like https://github.com/gwtbootstrap3/gwtbootstrap3/wiki/Setup-in-Intellij-IDEA for this?

**Comment by ArloL** [comment]
Sigh ;)

**Comment by ArloL** [comment]
Like this: https://github.com/gwtbootstrap3/gwtbootstrap3/wiki/Setup-in-Eclipse

**Comment by jgodi** [comment]
Yep, looks good. Thanks!
