### ISSUE TITLE
Add Mediator: GWT Bean Validation connected to Bootstrap FormGroup Validation State

### ISSUE THREAD

**Issue by davidbuhler** [gwtbootstrap3/gwtbootstrap3#179]
Suggest we create a Mediator to connect GWT's native JSR-303 Bean Validation support with Bootstrap's native Form Field validation.

The Mediator would add the field to the ConstraintValidation hashmap, and then return a list of valid and invalid fields, and update the fields with the validation state (either on key change or click).

As it is, the developer would need to roll his own.

http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#forms
http://www.gwtproject.org/doc/latest/DevGuideValidation.html

**Comment by jgodi** [comment]
@davidbuhler I am not familiar with this at all. Do you think you would have any time to submit a PR for this?

**Comment by worknperk** [comment]
@jgodi  I want to, but It would have to be between contract gigs. I think it would take me a week to get something up and running, but it would simplify matters quite a bit from a developer and user perspective.

**Comment by sjardine** [comment]
@worknperk I would be interested in your feedback on #287.  I created an example in the gwtbootstrap3-demo project.

Here is a link to the current example:
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#formsWithValidation

**Comment by worknperk** [comment]
That's cool. This weekend, I'll try and add it into my project to see how it works first-hand.

I'm not sure if this is overkill or not, but in our use-case, it helps to keep track of whether the form is valid, whether multiple forms are valid (think Wizard or a multi-step form that is about to be "published", and also, whether the form has changed from the original state (Is the form dirty?). We need to check the last use case before a user navigates away from a section of the application, or tries to navigate to a new URL with a dirty form (Facebook works the same way).

Those might be useful additions (extras), or they might be overkill, but this is handy!

Thanks!

**Comment by sjardine** [comment]
Ok. Cool. I think its responsibility of the Editor framework to keep track of most of those things. For instance you should be able to call isDirty on the editor driver to get the state of the editor.

Let me know what how it goes with your project.



On February 5, 2015 5:37:28 PM MST, worknperk <notifications@github.com> wrote:
>That's cool. This weekend, I'll try and add it into my project to see
>how it works first-hand.
>
>I'm not sure if this is overkill or not, but in our use-case, it helps
>to keep track of whether the form is valid, whether multiple forms are
>valid (think Wizard or a multi-step form that is about to be
>"published", and also, whether the form has changed from the original
>state (Is the form dirty?). We need to check the last use case before a
>user navigates away from a section of the application, or tries to
>navigate to a new URL with a dirty form (Facebook works the same way).
>
>Those might be useful additions (extras), or they might be overkill,
>but this is handy!
>
>Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gwtbootstrap3/gwtbootstrap3/issues/179#issuecomment-73160310

-- 
Sent from Kaiten Mail. Please excuse my brevity.

IMPORTANT: This email does not constitute a contract or an offer or acceptance of an offer to enter into a contract.  Further, this email may not be used to modify, supplement, novate, or waive any rights with respect to an existing contract or other binding commercial terms.

**Comment by jgodi** [comment]
@sjardine Would you say that #287 can close this or is there still work needed?

**Comment by sjardine** [comment]
I think that #287 is probably enough to close this but I would wait until @worknperk has a chance to play with it.

If you dont mind, let's wait until early next week.

**Comment by jgodi** [comment]
Sounds good. Thanks

**Comment by sjardine** [comment]
I think we should go ahead and close this.  I did some more research and testing this weekend and bean validation definitely works.  If we need additional validation implementations we probably should start a new issue.

**Comment by jgodi** [comment]
Thanks for the work on this!

**Comment by davidbuhler** [comment]
I wanted to look at it this weekend, but we are in the middle of a
migration to IntelliJ and Maven, which is still in progress.

I can tell you that the approach taken looks right, and is an extremely
handy compliment to how GWT works (Java), how the server side validation
works (JSR annotated validations), and has a nice tie in to Bootstrap.

I think a decision point might include a unit test that verifies the
validation routines work, and a test that verifies the ui displays the
correct message.

**Comment by worknperk** [comment]
Double thanks!
