### ISSUE TITLE
Modal don't remove modal-open when use History.back()

### ISSUE THREAD

**Issue by maveilletechno** [gwtbootstrap3/gwtbootstrap3#206]
Hi,

We try to use a Modal with a button which execute a History.back(). Seems that this action prevent Model to hide properly because "modal-open" style is not removed on the body, even if I add a myModal.hide() on my handler just before the back.

Let me know if you need more details or code.

Thanks,

**Comment by klimeryk** [comment]
@maveilletechno, could you provide more details? I can't seem to replicate this.
I created a modal, added a button and in the button's `ClickHandler`:

    modal.hide();
    History.back();

After clicking the button everything behaves as it should - the modal is getting hidden (or completely removed from DOM if `removeOnHide="true"`), the `<body>` element has the `modal-open` style removed and history goes back one item.

**Comment by jgodi** [comment]
I will keep this open for a few more days, if no response then I will close it. Thanks for investigating this @klimeryk

**Comment by maveilletechno** [comment]
Hi guys, sorry I had this issue during a mission for a customer and this mission is over. I don't have access to source code now. I'll try to reproduce on another project but no time today.

**Comment by jgodi** [comment]
Might pull this out of the 0.9 release then, until we can narrow this down more.

**Comment by ArloL** [comment]
IMO this can be closed.

**Comment by jgodi** [comment]
Agreed.
