### ISSUE TITLE
Upgrade to Bootstrap 3.2.0

### ISSUE THREAD

**Issue by svenjacobs** [gwtbootstrap3/gwtbootstrap3#214]
We should upgrade to [Bootstrap 3.2.0](http://blog.getbootstrap.com/2014/06/26/bootstrap-3-2-0-released/).

**Comment by crevete** [comment]
Now bootstrap should be upgraded to 3.3.2. I will make a PR including also :
 - jquery-1.11.2.min.js
 - fontawesome 4.3.0 with new IconTypes
