### ISSUE TITLE
Form doesn't have setEncoding and addSubmitComplete Handler methods

### ISSUE THREAD

**Issue by ask007java** [gwtbootstrap3/gwtbootstrap3#232]
I just migrated from gwtboostrap to gwtboostrap3 and realized that Form doesn't have setEncoding and addSubmitComplete Handler methods. These methods are essential for file uploading. Please let me know if this is an issue, or I am doing something wrong or how would you handle file uploading without those methods.

**Comment by jgodi** [comment]
Since the work with 0.9 is going so well, I would like to get this into the 0.9 release. Any way you can get a PR for this in the next few days?

**Comment by jgodi** [comment]
@slugmandrew or @donbeave Would one of you like to submit a PR for this issue? Then we can get it into the 0.9 release. Thanks!

**Comment by slugmandrew** [comment]
Not sure if I'll have time I'm afraid. I will give it a shot sometime soon though. For the time being I'm just doing it the way I described above.
