### ISSUE TITLE
Cannot set checked state on Radio widget

### ISSUE THREAD

**Issue by dharezlak** [gwtbootstrap3/gwtbootstrap3#238]
Using `setValue(true)` does not work.

**Comment by ArloL** [comment]
I sadly cannot reproduce the problem in Chrome or IE 8 using latest master or 0.8.1.

Could you write a small sample demonstrating the problem?

Thanks.

**Comment by dharezlak** [comment]
The setter works fine. My radio button was part of a form up in the hierarchy which was reset after the value was set on the radio button which looked like the setter was not working. Sorry for the trouble.

**Comment by ArloL** [comment]
Thanks for reporting back!
