### ISSUE TITLE
Add ButtonCell

### ISSUE THREAD

**Issue by rsertelon** [gwtbootstrap3/gwtbootstrap3#240]
Hi,

It would be really useful to have a ButtonCell with a Button inside.

I will try to implement one, and if satisfied, I will make a PR.

**Comment by jgodi** [comment]
@rsertelon @slugmandrew Any update on this? Would like to get a 0.9 release soon and have this in there!

**Comment by slugmandrew** [comment]
I was wondering the same thing. If @rsertelon hasn't made any progress I'm willing to give it a shot.

**Comment by rsertelon** [comment]
Will try to do it today. If I cannot, then I'll tell you so that @slugmandrew can try to as he proposed (in the next days, I'm afraid I won't have time) ;)

**Comment by rsertelon** [comment]
I've finally had time to push this. Does it seem okay to you all?
