### ISSUE TITLE
listbox in multiple selection mode - number of visible items ignored on mobile

### ISSUE THREAD

**Issue by biancashouse** [gwtbootstrap3/gwtbootstrap3#241]
In Chrome on my desktop, my listbox looked great. I had used setVisibleItemCount and setMultipleSelect.

On my ipad you only see one item and have to use the lisbox as a pull down to see the remaining items.
Multiple selection still works, but I did want to have all the items visible.

So I have used a listgroup of checkboxes as my workaround for now.

Thanks for a great API anyway. Hope this is helpful.

**Comment by ArloL** [comment]
I am not sure whether this is a problem with GWT Bootstrap.

Have you tried a vanilla select like 
~~~~~
<select name="select" size="2">
  <option value="value1">Value 1</option> 
  <option value="value2" selected>Value 2</option>
  <option value="value3">Value 3</option>
</select>
~~~~~

According to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attr-size) browsers are not required to display a scrolled ListBox.

**Comment by ArloL** [comment]
This is what the iOS simulator shows:

![ios simulator screen shot 03 02 2015 21 47 06](https://cloud.githubusercontent.com/assets/195367/6029057/3e7b94cc-abee-11e4-999a-dbe533fbffa5.png)

So I guess this issue can be closed.

**Comment by jgodi** [comment]
Thanks again @ArloL

**Comment by glenpierce** [comment]
I propose reopening this issue since it's still a bug. Yes, there's a work around, but I'm not sure this works well for multiselect listboxes.

**Comment by crevete** [comment]
Dis you try multiple select with size 2 or more on your mobile phone with jsfiddle or w3c school? The size attribute is just ignored. But you are still able to select multiple items when clicking on the select to show all items. This is a  choice of mobile browser, NOT a bug of gwtbootstrap3

**Comment by glenpierce** [comment]
If I select the items, it does give me a proper count of how many are selected.

Thanks for informing me that it's a mobile browser issue instead of a gwt issue.
