### ISSUE TITLE
0.9 release

### ISSUE THREAD

**Issue by ArloL** [gwtbootstrap3/gwtbootstrap3#247]
Currently there are four issues marked for the 0.9 milestone

https://github.com/gwtbootstrap3/gwtbootstrap3/milestones/0.9

Is this accurate?

I'd like to help get an 0.9 release out there.

**Comment by jgodi** [comment]
I will go through and update what would be ideal for 0.9.

**Comment by jgodi** [comment]
Ok updated the milestone for the main library and the extras: https://github.com/gwtbootstrap3/gwtbootstrap3-extras/milestones/0.9.

I will have some time next week to help out too. Thanks for the help!

**Comment by ArloL** [comment]
Hm there are some bugs that have a 1.0 milestone (e.g. #238). Shouldn't all bugs be fixed before we release a new version?

**Comment by jgodi** [comment]
Fixed, thank you.

**Comment by jgodi** [comment]
Coming along nicely, a few more issues to clean up. Thanks a lot @ArloL

**Comment by crevete** [comment]
@jgodi When you will release 0.9? Waiting for some fixes or features?

**Comment by jgodi** [comment]
Just waiting for everything on the Milestone: https://github.com/gwtbootstrap3/gwtbootstrap3/milestones/0.9. Same with extras.

I should have more time next week to dedicate to knock those out and get a release out.

**Comment by ArloL** [comment]
AFAI can see all 0.9 bugs are fixed. IMO we should release a snapshot, deploy a snapshot demo somewhere and have people test.

**Comment by jgodi** [comment]
Just cut new snapshots. if all is good by Wednesday or so. I will cut a new release. Thanks for all the help @ArloL

**Comment by ArloL** [comment]
No problem.

Did you also release a snapshot build of the demo somewhere?

**Comment by jgodi** [comment]
I will put the snapshot demos here for now on: http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot

Also, the API docs: http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/apidocs/

Will update the README and such to reflect this.

**Comment by jgodi** [comment]
Going to let these SNAPSHOTs linger out there for a day or two more, then I will cut a release.

Thanks @ArloL for all the help with getting this out.

**Comment by jgodi** [comment]
Writing the change log for the 0.9 releases and then we will cut the release

**Comment by rsertelon** [comment]
Great news! :)

**Comment by svenjacobs** [comment]
0.9 has just been released. It may take a few hours until it's available on Maven Central.

**Comment by remarkNS** [comment]
Great news ! Special congratulations to ArloL who "pushed" this project from idle state to new release.

**Comment by jgodi** [comment]
Yes, thanks to @ArloL @crevete @rsertelon, major help getting this out. Onward to v1.0!

**Comment by ArloL** [comment]
Great work!

**Comment by crevete** [comment]
That's pretty cool! Thanks to you all :-)

**Comment by rsertelon** [comment]
Great! Thanks a lot :)
