### ISSUE TITLE
ListItem setText adds text instead of replacing it.

### ISSUE THREAD

**Issue by rsertelon** [gwtbootstrap3/gwtbootstrap3#277]
Hi,

Calling `setText(...)` several times in a row will append text elements instead of replacing the text of the `ListItem`.

I can see in the code that the `add(...)` method is used to set text in `ListItem`, but not `clear()` is done before.

If you confirm that this is a bug, I could try to fix it via a PR.

**Comment by ArloL** [comment]
This should be in 0.9 milestone.
