### ISSUE TITLE
[Select] setValues does not show selected items when select is open

### ISSUE THREAD

**Issue by rsertelon** [gwtbootstrap3/gwtbootstrap3#284]
Hi,

When we use `setValues`, the `Select` component does have the expected values selected but it is not reflected when the select is open.

You can see this bug on the demo page, when clicking on the `setValues` button at the bottom of the page. When you open the `Select`, only `One` is shown as selected although it is actually not.

**EDIT** Link to demo page: https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#select

**Comment by jgodi** [comment]
This is for the extra's library, not the main GwtBootstrap3 library. Please open the issue there :)

**Comment by ArloL** [comment]
Snapshot demo works:

http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#select

**Comment by rsertelon** [comment]
@jgodi Sorry :)

@ArloL ok, so 0.9 should fix this then ^^
