### ISSUE TITLE
Passing Resources to CellTable does not style table

### ISSUE THREAD

**Issue by slugmandrew** [gwtbootstrap3/gwtbootstrap3#309]
Hey guys, I'm looking for a bit of clarification on this issue.

In GwtBootstrap3 there is a constructor: `public CellTable(final int pageSize, final Resources resources)`

If this was a standard GWT `CellTable` the `Resources` would allow a developer to style elements of the table with css, like this:

```
.cellTableHeader {
	background-color: #eee;
}
.cellTableSortableHeader {
	cursor: pointer;
}
.cellTableSortableHeader:hover {
	background-color: #ddd;
}
.cellTableCell {
	font-size: 13px;
}
```

I noticed that the current implementation of `CellTable` doesn't apply those classes to the table as the native GWT one would. They are all just `class="gwtb3-d"` whether sortable or not, etc.

Is there a way to achieve this? Is it something that could be included in a future PR? I see in the code for `CellTable` those classes have been deliberately removed to allow Bootstrap styling but wasn't sure exactly what was going on.

Cheers,

Drew

**Comment by jgodi** [comment]
Just use the native GWT `CellTable` if you do not want to have your's styled like a bootstrap table. We only have an implementation of `CellTable` so that we can provide the Resources to make it look/feel like a bootstrap table.

**Comment by slugmandrew** [comment]
The thing is, I want the bootstrap styles, but I also want to add a couple of very basic style rules on top of them - to change the colour of the header on hover if that column is sortable, for instance.

It's fine if it's just something that hasn't been implemented yet, I just thought I'd ask the question as I was trying to make sense of the `CellTable` code and didn't quite get what was going on.

**Comment by sjardine** [comment]
It depends on the type of styling you want but you should be able to use some custom css to do this via either a ui:style element in UIBinder or a global css file.
