### ISSUE TITLE
Demo v0.9 #forms not working

### ISSUE THREAD

**Issue by pofuk** [gwtbootstrap3/gwtbootstrap3#315]
There seems to be an error on page (FF, Chrome):

https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#forms

![2015-02-16 11_56_53-gwtbootstrap 3 demo](https://cloud.githubusercontent.com/assets/2906197/6210752/f9ff239c-b5d2-11e4-8065-0aeeac585e6b.png)

**Comment by jgodi** [comment]
@sjardine Mind looking at this?

**Comment by sjardine** [comment]
Sure.

Steven Jardine
Vice President
MJN Services, Inc.
801-705-9030 x102

On 02/16/2015 08:58 AM, Joshua Godi wrote:
>
> @sjardine <https://github.com/sjardine> Mind looking at this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gwtbootstrap3/gwtbootstrap3/issues/315#issuecomment-74529848>.Web 
> Bug from 
> https://github.com/notifications/beacon/AAWlYRBH5YzMLDQLL7qz-wLEu5vkXjp9ks5nsgszgaJpZM4Dg6n1.gif
>



IMPORTANT: This email does not constitute a contract or an offer or acceptance of an offer to enter into a contract.  Further, this email may not be used to modify, supplement, novate, or waive any rights with respect to an existing contract or other binding commercial terms.
