### ISSUE TITLE
Replacing "Sample" with "Seed"

### ISSUE THREAD

**Issue by worknperk** [gwtbootstrap3/gwtbootstrap3#321]
Hello,

I would propose nixing the sample project, and replacing it with a seed project. The seed project would be completely IDE independent, downloading all of the dependencies through Maven. Likewise, we'd use the latest gwt-maven-plugin to launch the application.

I would suspect most people who want to try the application out and build something small would prefer if they just had to clone a repo, call a couple goals, and see gwtbootstrap3 up and running.

Food for thought,
David

**Comment by sjardine** [comment]
Maybe I am missing something but I was able to successfully launch the gwtbootstrap3-demo project with the following maven command:

mvn clean package gwt:run

This launches the development mode app.  If you click "Launch Default Browser" it launches the demo app.  Isn't this the same thing as what you are proposing?

**Comment by jgodi** [comment]
I think he might be referring to: https://github.com/gwtbootstrap3/gwtbootstrap3-sample-app. Which was a thought to have a long time ago, but hasn't been maintained or anything as of recently.

**Comment by davidbuhler** [comment]
I am.

1) people search on seed apps. Call it a seed.
2) the seed app should have a read.me with setup instructions.
3) the seed should be decoupled from the other projects as far as repos go.
4) include some additional assets, much like html5 boilerplate for what lives on the webroot.
5) remove eclipse or intellij references. A pure maven pom is all you need for eclipse or intellij to understand the project nature.
6) include the latest dependencies.
7) make it the front and center showpiece with a github page. Link to the demo ans docs and forums from that github page.

**Comment by davidbuhler** [comment]
Think of it as, "Let's get started and make this as painles s and simple as possible".

**Comment by sjardine** [comment]
I think we should create a seed project as a replacement for the sample-app project.

**Comment by sjardine** [comment]
Added gwtbootstrap3-seed repository.
