### ISSUE TITLE
IconType.USER_PLUS has wrong stylename

### ISSUE THREAD

**Issue by vault13tech** [gwtbootstrap3/gwtbootstrap3#327]
gwtbootstrap3 version: v0.9

when I use IconType.USER_PLUS enum for an Icon, it display empty,
then I look into IconType and I found the enum USER_PLUS has a stylename "user-plus", 
shouldn't it be "fa-user-plus" ?

**Comment by sjardine** [comment]
Yeah.  I'll take care of this next PR.

**Comment by jgodi** [comment]
+1

**Comment by crevete** [comment]
@vault13tech my bad, my mistake...
