### ISSUE TITLE
Remove font-awesome dependency from NoThemeReasources module.

### ISSUE THREAD

**Issue by sjardine** [gwtbootstrap3/gwtbootstrap3#328]
Currently the NoThemeResources module has the line:

    <stylesheet src="css/font-awesome-4.3.0.min.cache.css"/>

This forces injection of the font-awesome css.  I think it would be a good idea to remove this requirement and force the user to manually add it if they want it.

Am I missing something?  Was this left in there for a reason?  Thanks!

**Comment by jgodi** [comment]
The NoTheme was primarily for the bootstrap css. But I can see this point.
