### ISSUE TITLE
Russian language for org.gwtbootstrap3.extras.select.client.ui.Select 

### ISSUE THREAD

**Issue by hondogo** [gwtbootstrap3/gwtbootstrap3#330]
There is already support fo russian language in js

Only changes needed:

in 
  org.gwtbootstrap3.extras.select.client.ClientBundle 
add
  @Source("resource/js/locales.cache.1.6.3/defaults-ru_RU.min.js")
    TextResource ru(); 

in 
  org.gwtbootstrap3.extras.select.client.constants.SelectLanguage
add
  RU("ru", SelectClientBundle.INSTANCE.ru()),

Thanks!

**Comment by jgodi** [comment]
This issue belongs in the GwtBootstrap3-Extra's project. Please recreate it there. Thanks!

https://github.com/gwtbootstrap3/gwtbootstrap3-extras
