### ISSUE TITLE
Alert's closed handler not working as expected

### ISSUE THREAD

**Issue by sainitarish** [gwtbootstrap3/gwtbootstrap3#335]
dismissibleAlert.addClosedHandler(...); is fired before alert gets removed from the parent, it was working earlier in gwtBootstrap3 .8 version

When clicking on close button it closes the alert but in parent widget (parent.getWidgetCount()) gives the count as 1 even after it has been removed.
Thanks

**Comment by jgodi** [comment]
Do you have time to submit a PR to fix this issue by chance?

**Comment by sainitarish** [comment]
Will check it!!!!

**Comment by sainitarish** [comment]
I tried removing it manually using removefromparent() method but somehow it seems to be an issue with Bootstrap library used in gwtBootstrap3 as it removes the UI from browser but does not update the parent DOM element, Where in it should update and remove that particular element from parent object.

If you have any fix or work around, Do let me know.

Thanks
