### ISSUE TITLE
Slider - range selection

### ISSUE THREAD

**Issue by nkg753** [gwtbootstrap3/gwtbootstrap3#337]
http://www.eyecon.ro/bootstrap-slider/

Slider value can be float or array. GwtBoostrap3 supports only float value. Array value is need for range slelection. I tried implement it but I have lack of experience in JavaScript. Can you implement it in 1.0 version?

**Comment by crevete** [comment]
@nkg753 The slider issue must be created in https://github.com/gwtbootstrap3/gwtbootstrap3-extras

FYI, the range slider has been implemented :
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#slider

**Comment by nkg753** [comment]
Thanks. It issue should be closed.
