### ISSUE TITLE
Memory leak with jQuery cache

### ISSUE THREAD

**Issue by PaulKC** [gwtbootstrap3/gwtbootstrap3#339]
Hello

I do have a problem with memory leaks in my application which uses bootstrap and gwt. I don't use gwtbootstrap3 in this project but I see the same problem on your demo page.
For components which use bootstrap js (Tooltip, Modal, ... ) a object is created in $.cache the problem is that this entry prevents the DOM objects from being garbage collected even if they are detached.

Regards Kenny

**Comment by jgodi** [comment]
@crevete Have you seen this? Is it because the *.cache.js files?

**Comment by crevete** [comment]
@jgodi Yeah it's really a bug. I've tested a simple case : after calling the ```destroy``` method, the tooltip cached in $.cache is never removed. I guess it's a bug in bootstrap.js. Not sure it's due to *.cache.js files.
Anyway, there is also a bug in ```Tooltip.java``` : when the wrapping widget is detached from DOM, we destroy the tooltip but still re-create a new one.

**Comment by sjardine** [comment]
@crevete This is most likely a bug with either the bootstrap or javascript libraries.  Since we no longer call recreate with Tooltip and Popover I don't see there being much need to investigate this further.  Do you have any thoughts?

**Comment by crevete** [comment]
@sjardine I agree with you. The same issue appears in the bootstrap home page: every visited widget is cached in ```$.cache```. As the tooltip issue was fixed (a real bug), this could also be closed. We could re-open this later if necessary.

**Comment by gregsheremeta** [comment]
For reference, I think I created a reproducer upstream, https://github.com/twbs/bootstrap/issues/17973#issuecomment-202648725
