### ISSUE TITLE
Description documentation fix

### ISSUE THREAD

**Issue by nkg753** [gwtbootstrap3/gwtbootstrap3#340]
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#typography

Is:  ```<b:DescriptionDescription text=""/>```
Should be: ```<b:DescriptionData text=""/>```

**Comment by jgodi** [comment]
For the future, this issue belongs in the https://github.com/gwtbootstrap3/gwtbootstrap3-demo project. Fixed now though. Thanks!
