### ISSUE TITLE
v0.9.1

### ISSUE THREAD

**Issue by jgodi** [gwtbootstrap3/gwtbootstrap3#342]
Releasing new SNAPSHOTs now, waiting for end of week to release v0.9.1.

**Comment by jgodi** [comment]
New SNAPSHOT Demo Up: http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/

Please test during week if you can! (Might take a little bit to load :))

**Comment by jgodi** [comment]
Sorry, my plan was to do this last weekend but could not find the time. Hopefully soon! Sorry :(

**Comment by jgodi** [comment]
Done, should be out on maven central soon.

**Comment by slugmandrew** [comment]
Great work! Any schedule for 1.0? I'd like to contribute more if I can.
