### ISSUE TITLE
ValueListBox is missing support for validation

### ISSUE THREAD

**Issue by timeu** [gwtbootstrap3/gwtbootstrap3#343]
Currently it is not possible to use `Validation` (BeanValidation or BlankValidation) with the [ValueListBox](https://github.com/gwtbootstrap3/gwtbootstrap3/blob/master/gwtbootstrap3/src/main/java/org/gwtbootstrap3/client/ui/ValueListBox.java). In my simple test it should be enough to have the `ValueListBox` implement the `HasEditorErrors<T>`, `HasErrorHandler`, `HasValidators<T>`, `HasBlankValidator<T>` interfaces and copy the implementation from the [ValueBoxBase](https://github.com/gwtbootstrap3/gwtbootstrap3/blob/master/gwtbootstrap3/src/main/java/org/gwtbootstrap3/client/ui/base/ValueBoxBase.java). 

I can create a pull request.

**Comment by slugmandrew** [comment]
Hey buddy. Have a look at https://github.com/slugmandrew/gwtbootstrap3/commit/3fbe64c236cc167d2e828c99f859be14948202b1

I am learning to use the validation myself atm and I needed `HasId` so I thought this might be of use? I was interested to learn how the mixins work anyway.

What about adding `HasSize`, `HasResponsiveness`, `HasPlaceholder` as well?

**Comment by sjardine** [comment]
Please create a PR for this.  I guess I missed this one.  Thanks!

**Comment by timeu** [comment]
@slugmandrew Coo. As you already have the changes. Could you just create a pull-request ? I guess `HasPlaceholder` and `HasSize` also makes sense.

**Comment by jgodi** [comment]
+1 thanks!

**Comment by slugmandrew** [comment]
Done :)

**Comment by timeu** [comment]
Awesomem thanks ;-)
