### ISSUE TITLE
Pagination takes a SimplePager instead of an AbstractPager

### ISSUE THREAD

**Issue by timeu** [gwtbootstrap3/gwtbootstrap3#345]
Is there any reason why the `rebuild` function inside of [Pagination](https://github.com/gwtbootstrap3/gwtbootstrap3/blob/master/gwtbootstrap3/src/main/java/org/gwtbootstrap3/client/ui/Pagination.java) takes a `SimplePager` instead of an `AbstractPager` ? 

It should take the more abstract `AbstractPager`.

**Comment by jgodi** [comment]
The methods of `getPageCount` and `previousPage` are protected on the `AbstractPager` that is why we are using `SimplePager`.

We will welcome a PR if you find a better option. Thanks for reporting this.
