### ISSUE TITLE
Select Implementation

### ISSUE THREAD

**Issue by sjardine** [gwtbootstrap3/gwtbootstrap3#346]
Is there a reason that Select has not been implemented?  I realize that there is a js wrapper for bootstrap-select in the extras package but it seems like a basic stylized select should be included in the main project.  This would eliminate the need for 50K worth of javascript when a basic select would do.

Thoughts?

**Comment by jgodi** [comment]
I am game for one.

**Comment by sjardine** [comment]
Actually ListBox coveres the implementation I was thinking of.
