### ISSUE TITLE
Conflict with GWTUpload?

### ISSUE THREAD

**Issue by rsertelon** [gwtbootstrap3/gwtbootstrap3#350]
Hi,

I'm using [gwtupload](https://github.com/manolo/gwtupload) and it seems that migrating gwtbootstrap3 (and gwtbootstrap3-extras) from 0.8.1 to 0.9.1 breaks gwtupload's uploader.

I've checked several times before deciding to post this issue, as it seems very weird that gwtbootstrap3 can influence gwtupload.

I will try to find out what could cause this, it may have no link with gwtbootstrap3, I hope so :)

Does anyone else have seen this problem?

Thanks,

**Comment by jgodi** [comment]
Do you have sample code? or error by chance?

**Comment by rsertelon** [comment]
I'm afraid I've got no error, and as for the code, I don't have any piece ready.

I can try to make one, but can't promise, I've got lots to do currently.

Concerning the gwtupload problem with gwtbootstrap3: it actually works, but wait until the end of its retry policy to call `onFinishUpload`. This leads to 2 to 3 minutes waiting before the download shows as finished (even though it could have been done in less than a second).

Downgrading GWTBootstrap3 fixed the problem for me. But I don't see why it should be related.

Does GWTBootstrap3 overrides some of GWT's methods?

**Comment by jgodi** [comment]
We don't. What pieces of the library do you use? We are just a wrapper on Bootstrap.

**Comment by rsertelon** [comment]
I'm using the core library, and some extras: DateTimePicker, ToggleSwitch and Bootbox.

I plan to get rid of GWTUpload in the future, so it won't block us from upgrading to 0.9.1 and forward.

Was just asking here in case someone else got the problem...

**Comment by sjardine** [comment]
Closing this due to lack of information.  Please provide a test case illustrating the problem and we will re-open.
