### ISSUE TITLE
Allow TabListItem to accept widgets instead of just text

### ISSUE THREAD

**Issue by slugmandrew** [gwtbootstrap3/gwtbootstrap3#351]
I was wondering how people would feel about allowing `TabListItem` to accept children such as `Icon` and `Badge`?

This would be a good feature for the library IMO and I believe vanilla bootstrap allows this. I'm guessing we would have to make `TabListItem` implement `HasWidgets` and `HasIcon`. Currently it implements `HasText` so I get this error:

> Illegal child <b:Badge> in a text-only context. Perhaps you are trying to use unescaped HTML where text is required, as in a HasText widget?: <b:TabListItem active='true' dataTarget='#info' ui:field='infoTab'>

Code:
```xml
<b:TabListItem ui:field="infoTab" dataTarget="#info" active="true" icon="PLUS">
    Info
    <b:Badge>0</b:Badge>
</b:TabListItem>
```

http://getbootstrap.com/components/#badges

What do people think? I'm happy to try and implement it, but thought I'd ask for some feedback as I obviously want to do it in keeping with the design decisions of the library.

**Comment by jgodi** [comment]
I am game for it. Would love to see a PR for this.

**Comment by slugmandrew** [comment]
Great! I'll try to have a look at how those interfaces are implemented tonight or weekend but it might be more like next week.

If anyone has any suggestions or tips/advice it would be greatly received. Otherwise I'll just see what I can do.

**Comment by slugmandrew** [comment]
From looking at `Heading` I've gained a bit more insight now I think. I get that the constructors are only for creating objects from code, and not used by uiBinder apart from the `@UiConstructor` annotated one. I get that the properties of the uiBinder tag match up with the setters in the class, so `text="Tab One"` basically calls `setText("Tab One")`.

I also realised that `AbstractAnchorListItem implements HasIcon` already so code like `<b:TabListItem dataTarget="#comments" text="Comments" icon="CHECK" iconSize="LARGE" />` works and adds a nice icon in to the start of the tab.

So far so good...

BUT I'm quite confused by what happens when the `Heading` is created this way:

    <b:Heading size="H1">
        <b:Icon type="CHECK" />
        <b.html:Text text="Heading with icon" />
    </b:Heading>

instead of this way:

    <b:Heading size="H1" text="Heading Text" subText="Subtext Text"/>

Is it even possible to construct the tab's content this way, with it extending from `AbstractAnchorListItem`? I notice that `Heading` is basically a `ComplexPanel` so is it just calling `add()` on each one?

What about just allowing a String to be passed in to `setBadge(String badgeText)`. We could even create a `HasBadge` or even a `BadgeMixin` so we can add badges to other elements?

I'm gonna spend some more time looking at the mixins as this seems to be where the action happens. Atm I can only add a `Badge` before or after the entire tab :/

**Comment by slugmandrew** [comment]
OK, I think I'm getting there.

First draft:

https://github.com/slugmandrew/gwtbootstrap3/commit/3c7518bb06c0ed4115fe83b9c9849f992143fc9e

Let me know if I'm along the right lines.

Some output:

![tabs](https://cloud.githubusercontent.com/assets/153625/7887011/ddad0788-0625-11e5-92b2-0379a5b58a31.PNG)

I realise my eclipse has buggered up the formatting in a few places. Also probably need a few more constructors, etc.

Thoughts?

**Comment by remarkNS** [comment]
Example image is looking great.

**Comment by slugmandrew** [comment]
@sjardine As you seem the be the only one committing atm, do you want to comment on this at all? I can't get a response out of @jgodi for love nor money

**Comment by sjardine** [comment]
I have been working more in the form validation area for the most part but I will try and spend a few minutes looking over your first draft tonight or tomorrow.

**Comment by sjardine** [comment]
I think the implementation is fine and consistent with the current codebase. I can see a need for both ions and badges in the tab so I would +1 a PR for this enhancement.  I would fix the formatting though...

As for @jgodi not responding....I'm sure you weren't really offering money. That would most assuredly do it. ;) Seriously though, we are all busy and this is a volunteer effort so sometimes things take longer than others would like.

Cheers!

**Comment by slugmandrew** [comment]
Oh I totally understand, we all have jobs and lives etc and it's amazing the job everyone has done so far. I just got thought maybe he was away for along period or something because I didn't even get a "yes", "no" or "I'm a bit busy" after quite a few weeks. It's cool though I'll just assume I'm on the right track.

So.. thanks for the feedback. I am using IntelliJ now so the formatting shouldn't be an issue, it just needs to be fleshed out a little to get a proper PR up.

BTW, the form validation is really appreciated, I've been experimenting and plan to use it more very soon :) I'm not giving you any money though ;) Cheers!

**Comment by sjardine** [comment]
@slugmandrew Any update on this PR?  I am trying to finish up several of our open issues.

**Comment by slugmandrew** [comment]
I'm still working on it. I'll see if I can submit a PR this weekend
