### ISSUE TITLE
Maven artifacts have inconsistent version numbers on the central repository

### ISSUE THREAD

**Issue by ccidral** [gwtbootstrap3/gwtbootstrap3#352]
The `gwtbootstrap3` artifact (latest version, `0.9.1`) in the central repository makes a reference to `gwtbootstrap3-parent` version `1.0-SNAPSHOT` which does not exist in the repository causing a build error in projects that depend on `gwtbootstrap3`.

This is the offending part of `gwtbootstrap3`'s POM file in the central repository:

```xml
<parent>
  <groupId>org.gwtbootstrap3</groupId>
  <artifactId>gwtbootstrap3-parent</artifactId>
  <version>1.0-SNAPSHOT</version>
</parent>
```

It should be:

```xml
<parent>
  <groupId>org.gwtbootstrap3</groupId>
  <artifactId>gwtbootstrap3-parent</artifactId>
  <version>0.9.1</version>
</parent>
```

The build error that occurs in dependent projects:

```
[ERROR] Failed to execute goal on project example1:
Could not resolve dependencies for project example1:example1:war:1.0-SNAPSHOT:
Failed to collect dependencies at org.gwtbootstrap3:gwtbootstrap3:jar:0.9.1:
Failed to read artifact descriptor for org.gwtbootstrap3:gwtbootstrap3:jar:0.9.1:
Could not find artifact org.gwtbootstrap3:gwtbootstrap3-parent:pom:1.0-SNAPSHOT -> [Help 1]
```

**Comment by jgodi** [comment]
I will fix this asap. Sorry for the mishap!

**Comment by ccidral** [comment]
No problem! I worked around it by downloading the 0.9.1 sources and building the project locally.

**Comment by jgodi** [comment]
Redeploying now, should be good soon. Thanks!
