### ISSUE TITLE
onSlid and onSlide of Carousel Event Handlers don't work at GWT Super Dev Mode

### ISSUE THREAD

**Issue by julioheitor** [gwtbootstrap3/gwtbootstrap3#355]

**Comment by sjardine** [comment]
Please provide more information and possibly a small test case to illustrate the problem.

**Comment by julioheitor** [comment]
I added two handlers and put a Window.alert("bla bla") inside each one. None of the messages appears in any moment. The slides are changed properly by the Carousel, but no message appears on the screen. But if i run the example in GWT Debug mode, the messages appear properly:

org.gwtbootstrap3.client.ui.Carousel carousel = new Carousel();
carousel .addSlideHandler(new CarouselSlideHandler() {
			
			@Override
			public void onSlide(CarouselSlideEvent carouselSlideEvent) {
				Window.alert("blabla");
			}
		});
		
		carousel .addSlidHandler(new CarouselSlidHandler() {
			
			@Override
			public void onSlid(CarouselSlidEvent carouselSlideEvent) {
				Window.alert("blabla");
			}
		});

**Comment by julioheitor** [comment]
Just another extra info: The carousel is being styled using the Metro UI CSS Bootstrap (you can google it!).

**Comment by sjardine** [comment]
I cannot seem to duplicate this issue.  I have modified the CarouselView (see below) in the gwtbootstrap3-demo using your example and all events are working.

In order to further investigate I will probably need a small project that exhibits your problem. 

Steve

```
public class CarouselView extends ViewImpl implements CarouselPresenter.MyView {

    interface Binder extends UiBinder<Widget, CarouselView> {
    }

    @UiField
    protected Carousel carousel;

    @Inject
    CarouselView(final Binder uiBinder) {
        initWidget(uiBinder.createAndBindUi(this));
        carousel.getElement().setAttribute("class", "carousel");
        carousel.getElement().setAttribute("data-height", "420");
        carousel.getElement().setAttribute("data-effect", "fade");
        carousel.addSlideHandler(new CarouselSlideHandler() {
            @Override
            public void onSlide(CarouselSlideEvent carouselSlideEvent) {
                Window.alert("onSlide");
            }
        });
        carousel.addSlidHandler(new CarouselSlidHandler() {
            @Override
            public void onSlid(CarouselSlidEvent carouselSlidEvent) {
                Window.alert("onSlid");
            }
        });
    }

}
```

**Comment by julioheitor** [comment]
Here, put this code inside the onModuleLoad() method in the EntryPoint class. Notice: there is a lot of Metro UI CSS JavaScript underneath the project. So, there might be a chance that this JS is breaking something:

,,,
	final Image image1 = new Image(ImageProvider.IMPL.mainImage5());
		image1.getElement().getStyle().setZIndex(1);
		image1.getElement().setAttribute("position", "relative");
		image1.getElement().getStyle().setMarginTop(-20, Unit.PCT);
		//Animate.animate(image1, Animation.WOBBLE, 1, 19000);
		
		final Image image2 = new Image(ImageProvider.IMPL.mainImage7());
		image2.getElement().getStyle().setZIndex(1);
		image2.getElement().setAttribute("position", "relative");
		
		//Animate.animate(image1, Animation.ZOOM_IN_LEFT, 1, 50);
		final Image image3 = new Image(ImageProvider.IMPL.mainImage7());
		image3.getElement().getStyle().setZIndex(1);
		image3.getElement().setAttribute("position", "relative");
		image3.getElement().getStyle().setMarginTop(-20, Unit.PCT);
		//Animate.animate(image1, Animation.ZOOM_IN_LEFT, 1, 50);
		
		Div slide1 = new Div();
		slide1.getElement().setAttribute("class", "slide");
		
	    Div slide2 = new Div();
	    slide2.getElement().setAttribute("class", "slide");
	  
		Div slide3 = new Div();
		slide2.getElement().setAttribute("class", "slide");
	
		slide1.add(image1);
		slide2.add(image2);
		slide3.add(image3);
		
		Carousel carousel = new Carousel();
		carousel.getElement().setAttribute("class", "carousel");
		carousel.getElement().setAttribute("data-height", "420");
		carousel.getElement().setAttribute("data-effect", "fade");
		carousel.getElement().setAttribute("data-period", "5500");
		carousel.getElement().setAttribute("data-duration", "1500");
		carousel.getElement().setAttribute("data-markers-position", "bottom-right");
		carousel.getElement().setAttribute("data-markers-show", "true");
		carousel.getElement().setAttribute("data-stop", "false");
		carousel.getElement().getStyle().setProperty("minWidth","1600px");
		carousel.getElement().getStyle().setZIndex(1);
		carousel.getElement().getStyle().setPosition(Position.ABSOLUTE);
		
		carousel.add(slide1);
		carousel.add(slide2);
		carousel.add(slide3);
		
		carousel.addSlideHandler(new CarouselSlideHandler() {
			
			@Override
			public void onSlide(CarouselSlideEvent carouselSlideEvent) {
				//Animate.animate(introPanel.getActualPhrase(), Animation.LIGHTSPEED_OUT, 1, 1500);
				Window.alert("Alerta 1!");
			}
		});
		
		carousel.addSlidHandler(new CarouselSlidHandler() {
			
			@Override
			public void onSlid(CarouselSlidEvent carouselSlideEvent) {
				//introPanel.getActualPhrase().setVisible(false);
				//SplashPhrase next = introPanel.nextSplashPhrase();
				//next.setVisible(true);
				//Animate.animate(next, Animation.LIGHTSPEED_IN, 1, 1500);
				Window.alert("Alerta 3!");
			}
		});
		
		RootPanel.getBodyElement().setAttribute("class", "metro");
		RootPanel.get().add(carousel);

,,,

**Comment by julioheitor** [comment]
Any news?

**Comment by sjardine** [comment]
I have tested your code and the events fire as expected.  My guess that MetroUI and the Carousel widget don't play nice together.  

Also, next time please make sure your code works (the above doesn't compile) and exhibits the problem you describe.  Thanks!

@jgodi - I would close this as invalid unless @julioheitor sends a valid test case that can show otherwise.

**Comment by jgodi** [comment]
Thanks for diving into this @sjardine. Closing this for now, will reopen if needed.

**Comment by julioheitor** [comment]
I am really sorry about the bad code. Really am. I forgot that the ImageProvider only exists in my project.

And you were right! The problem is indeed the connection between MetroUI and the Carousel Widget.

When i commented the code part "RootPanel.getBodyElement().setAttribute("class", "metro");", all of a sudden the events started to fire!

Thank you very much for your support, attention and specially your pacience!
