### ISSUE TITLE
Add validation support for the ListBox widget

### ISSUE THREAD

**Issue by mickaelbaron** [gwtbootstrap3/gwtbootstrap3#364]
Hi,

I found this issue on gwtbootstrap3-extra (https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/164).

I think i would be useful to add validation support for ListBox. This validator could be check if an item has been selected (BlankValidator)

What about this idea ?

**Comment by sjardine** [comment]
ValueListBox has validation methods.


On May 13, 2015 2:39:50 PM MDT, Mickael BARON <notifications@github.com> wrote:
>Hi,
>
>I found this issue on gwtbootstrap3-extra
>(https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/164).
>
>I think i would be useful to add validation support for ListBox. This
>validator could be check if an item has been selected (BlankValidator)
>
>What about this idea ? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gwtbootstrap3/gwtbootstrap3/issues/364


IMPORTANT: This email does not constitute a contract or an offer or acceptance of an offer to enter into a contract.  Further, this email may not be used to modify, supplement, novate, or waive any rights with respect to an existing contract or other binding commercial terms.

**Comment by mickaelbaron** [comment]
Hi Steven,

I didn't think about this class. 

The GWTBootstrap3 widgets which support valiation implement the HasValidators interface. With this implementation we can get invalid message into form for example.

Mickael

**Comment by sjardine** [comment]
I think we can close this.

**Comment by mickaelbaron** [comment]
Sorry we cannot close this issue because ListBox doesn't yet implement the HasValidators interface.

We could pass this issue to as an enhancement label, isn't it ?

Mickael

**Comment by sjardine** [comment]
Sorry. I don't really agree.  ListBox is not part of the gwt editor framework which is necessary for JSR-303 and our client side validation to work.  I believe this is the reason ValueListBox was created by the gwt team.  If you really need validation for ListBox you should create a Composite that implements the Editor, HasValue, and the other validation and error handler interfaces.

@jgodi, @ArloL:  I suggest we close this issue as a "won't fix" until the gwt team adds ListBox to the editor framework.
