### ISSUE TITLE
DateTimePicker left/right arrow perform different action

### ISSUE THREAD

**Issue by Unimax** [gwtbootstrap3/gwtbootstrap3#365]
recreate:
click on right/left arrow on difference places will zoomin in some cases and forward date in some cases. 

arrow icon seems smaller then the div (not sure this is the reason of issue).

issue is with latest datetimepicker of gwtbootstrap3-extras

**Comment by slugmandrew** [comment]
I think this is a known issue more to do with bootstrap than gwtbootstrap. There is another issue somewhere I believe

**Comment by slugmandrew** [comment]
Found it https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/140

**Comment by Unimax** [comment]
@slugmandrew thanks, i just found the same.
