### ISSUE TITLE
Tooltip disappeared when reconfigure method was called twice

### ISSUE THREAD

**Issue by binarier** [gwtbootstrap3/gwtbootstrap3#367]
here's a very simple test case
```java
public class Sample implements EntryPoint
{
	/**
	 * This is the entry point method.
	 */
	public void onModuleLoad()
	{
		final Button btn = new Button("Reconfigure");
		final TextBox field = new TextBox();
		final Tooltip tt = new Tooltip(field);

		RootPanel.get("container").add(tt);
		RootPanel.get("container").add(btn);
		
		btn.addClickHandler(new ClickHandler()
		{
			
			@Override
			public void onClick(ClickEvent event)
			{
				tt.setTrigger(Trigger.FOCUS);
				tt.setTitle("hello world");
				tt.reconfigure();
			}
		});
	}
}
```

The tooltip can be shown when the "reconfigure" button was clicked and the textbox was focused; and click the button **again**, tooltip **disappeared**; and tooltip would **come back** if we click the button **3rd time**.

maybe there's some problem in the reconfigure method

**Comment by sjardine** [comment]
I have experienced this issue myself.  I am not sure this relates to #339 but it seems like we should rework the Tooltip code.

**Comment by crevete** [comment]
@sjardine @binarier I have also experienced this issue. It's a problem with the animation... I have just found a workaround :

```
final Tooltip tt = new Tooltip(field);
tt.setIsAnimated(false);
```

If you deactivate the animation which is activated by default, the ```reconfigure()``` works fine. Anyway, this is just a workaround, not the clear way to make it work. I don't if it's a bug from bootstrap JS or our GWT wrapper.

**Comment by crevete** [comment]
And the same problem occurs in the ```Popover``` widget with the same workaround...
