### ISSUE TITLE
NavbarText missing style value

### ISSUE THREAD

**Issue by worknperk** [gwtbootstrap3/gwtbootstrap3#373]
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#navbar

The NavbarText sites flush with the Navbar. The padding or margin has disappeared.

![capture](https://cloud.githubusercontent.com/assets/10578022/8636128/007cc026-281f-11e5-9166-e49c00b31af0.PNG)

**Comment by worknperk** [comment]
as a temporary work-around for people with the same issue:
@media ( min-width : 768px) {
	.navbar-right {
		margin-right: 15px !important;;
	}
}

**Comment by sjardine** [comment]
This is not a bug with gwtbootstrap3.  The bootstrap css specifies the "margin-right: -15px".
