### ISSUE TITLE
GWT Grid, FlexTable conflict

### ISSUE THREAD

**Issue by parkjaehyuck** [gwtbootstrap3/gwtbootstrap3#374]
sorry I can't write English.

GWT SDK 2.7
JAVA 1.7

gwtboootstramp3 0.9.1

problem..

Grid grid = new Grid(2,1);
grid.setCellPadding(4);  <-- not working
grid.setCellSpacing(4);  <-- not working

FlexTable table = new FlexTable();
table.setCellPadding(4);  <-- not working
table.setCellSpacing(4);  <-- not working

**Comment by slugmandrew** [comment]
This is the wrong place to be asking a question like this. You should ask on stackoverflow.com and provide more information about what you are doing and the errors you are seeing.

This doesn't seem to anything to do with gwtbootstrap3 as `Grid` and `FlexTable` are GWT classes.
