### ISSUE TITLE
AbstractForm method fireSubmitEvent fires wrong event type

### ISSUE THREAD

**Issue by vinssor** [gwtbootstrap3/gwtbootstrap3#375]
The AbstractForm method fireSubmitEvent fires a FormPanel.SubmitEvent and not an AbstractForm.SubmitEvent

**Comment by sjardine** [comment]
I'm not sure that this really matters, however, we should probably be consistent with how we handle SubmitEvent and SubmitCompleteEvent.

**Comment by manstis** [comment]
Yay :) -- I've just been debugging why this never fires when the form is submitted:-

```
form.addSubmitHandler( new AbstractForm.SubmitHandler() {
            @Override
            public void onSubmit( final AbstractForm.SubmitEvent event ) {
                //Do something, anything!
            }
        } );
```
