### ISSUE TITLE
Accordion panel headers not working on ipad

### ISSUE THREAD

**Issue by invader35** [gwtbootstrap3/gwtbootstrap3#376]
Hi there,

I got a problem using the accordion panel headers on the ipad. (this is only valid for the whole header clickable variant)

When I tap the header it is not expanding as expected.
Is there a workaround for gwtbootstrap3 available? 
I only found one for using bootstrap 3 directly
(Source: https://notsomany.wordpress.com/2015/02/12/bootstrap-collapse-ios-issue/
http://stackoverflow.com/questions/19866172/bootstrap-3-accordion-collapse-does-not-work-on-iphone)

Thanks in advance

**Comment by sjardine** [comment]
Well according to the acceptable answer on stack trace you could set the href to the id of the data target in order to achieve the same result as they did in the answer.

**Comment by sjardine** [comment]
This is really a bootstrap issue not a gwtbootstrap3 issue.  The workaround for this is in the above posts.
