### ISSUE TITLE
Tooltip setText method missing, instead of deprecated in GwtBootstrap 0.9.1

### ISSUE THREAD

**Issue by StTheo** [gwtbootstrap3/gwtbootstrap3#377]
Why was this method completely removed? I thought that a "setText" method was helpful in that it was consistent across the various text-based widgets.

Now, even if there is a decent reason to remove this, it needs to be deprecated (preferably with an explanation as to why it was deprecated). I just spent two hours rummaging through gin exceptions, then rummaging through gwt exceptions, then commenting out all of the ui in the offending class and uncommenting them one-by-one to discover this.

**Comment by BenDol** [comment]
was re-added in the next release, I believe.

**Comment by sjardine** [comment]
I just verified that this was **NOT** re-added.  It was just a convenience method so I probably would have left it there.  I don't feel too inclined to re-add it though. Thoughts?

**Comment by StTheo** [comment]
As far as GWT-consistency goes, it's debatable whether or not setTitle or setText is more appropriate. With GWT, setTitle is used to determine what the tooltip text should be when hovering over a widget - though, I guess this would be that tooltip. However, this is also a widget that exists primarily to show text, which I would argue not only should have the setText method, but also should implement the HasText interface (which is helpful for exposing the text setters/getters for a widget in MVP).

If this is kept out of the class, I would ask that we keep a list of potentially breaking changes like this, similar to the 0.7 to 0.8 update guide. We use GwtBootstrap3 extensively in a very large project, and relatively small changes like this can cause big, difficult to diagnose problems.

**Comment by BenDol** [comment]
setText makes more sense to me since setTitle in other GWT widgets makes it misleading.
