### ISSUE TITLE
Looking for help maintaining this library!

### ISSUE THREAD

**Issue by jgodi** [gwtbootstrap3/gwtbootstrap3#381]
If you are interested please get in touch with me. Both @svenjacobs and I are very busy in other project and would appreciate some help!

Thanks!

**Comment by sjardine** [comment]
I would be willing to help maintain.

**Comment by jgodi** [comment]
Awesome, you have already been a great contributor as well. Would like one more to help as well, @crevete? :)

**Comment by crevete** [comment]
Yep, I'd like to help you to maintain this lib :-)

**Comment by jgodi** [comment]
Awesome, you two have done an amazing job already. I will add you guys as maintainers and email you guys out instructions on how to deploy SNAPSHOTs and releases. Thanks, we really appreciate it.

**Comment by jgodi** [comment]
If you guys can shoot me an email at joshuagodi@gmail.com and I can send you that stuff, that would be great! I added you guys as maintainers, you should be free to merge PRs, close issues, whatever you guys need to be done.
