### ISSUE TITLE
AbstractForm frame name conflicts with GWT FormPanel resulting in onSubmitCompleteEvent not being received

### ISSUE THREAD

**Issue by tbps** [gwtbootstrap3/gwtbootstrap3#384]
Hi, 

AbstractForm uses "FormPanel_" as frame name creating conflicts with FormPanel.

Say you have a page with 2 forms: a GwtBootstrap form and a Gwt FormPanel (containing an upload form), this will result in having the following iFrames:
- FormPanel_myModule_1 for the GwtBootstrap form
- FormPanel_myModule_1 for the Gwt FormPanel

Because there are 2 iFrames with the same name in the DOM, the onSubmitComplete event of the upload form will not be received properly. 

To fix this you need to change the line 269 of AbstractForm and replace  
frameName = "FormPanel_" + GWT.getModuleName() + "_" + (++formId); 
with 
 frameName = "GwtBootstrapFormPanel_" + GWT.getModuleName() + "_" + (++formId);

This issue had previously been reported in the old version of gwt boostrap: https://github.com/gwtbootstrap/gwt-bootstrap/issues/363

**Comment by sjardine** [comment]
Fixed with PR #385.
