### ISSUE TITLE
DataTargetMixin.setDataTargetWidget() is overwriting element id's

### ISSUE THREAD

**Issue by p33t** [gwtbootstrap3/gwtbootstrap3#391]
DataTargetMixin.setDataTargetWidget() appears to [overwrite an element's id](https://github.com/gwtbootstrap3/gwtbootstrap3/blob/master/gwtbootstrap3/src/main/java/org/gwtbootstrap3/client/ui/base/mixin/DataTargetMixin.java#L44) without checking if it is already set.

This is a problem when multiple elements target the same widget (like carousel indicators and controls), and [Java code](http://b-generation.freshcode.biz) (not UI Binder) is used to construct the interface.

Perhaps the id could be set IFF it does not already have an id?

**Comment by sjardine** [comment]
Sure. Would you be willing to submit a PR?

**Comment by p33t** [comment]
FYI, I tested this fix with [carousels in my learning project](https://subversion.assembla.com/svn/freshcode_public/learn/gwt-bootstrap/src/main/java/biz/freshcode/learn/gwt_bootstrap/client/carousels/Carousels.java) and it seems fine.
