### ISSUE TITLE
Unable to switch tabs on a modal popup after the first time its invoked

### ISSUE THREAD

**Issue by ialexei** [gwtbootstrap3/gwtbootstrap3#394]
To reproduce this, place Navbar and TabContent on a modal popup.
The first time, the tabs will switch as intended.
Invoking a new instance of the dialog again, will display the nav items and the initial tab content, but user will be unable to switch between tab items.

If somebody is willing to look at it, I can write a sample to demonstrate the issue.

**Comment by crevete** [comment]
A sample code is welcome

**Comment by ialexei** [comment]
Here you go...
https://github.com/ialexei/gwtbootstrap3-sample-app

**Comment by ialexei** [comment]
Hi,

Were you able to run the sample and see the issue ?

-Alexei

**Comment by sjardine** [comment]
Thanks for the sample code.  There definitely is a bug here but I am not sure if it is a gwtbootstrap3 issue or bootstrap issue.

**Comment by sjardine** [comment]
This definitely it a gwtbootstrap3 issues.  I created a small bootstrap test that works without problems.

    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"   />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-  theme.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div id="myModal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#home" aria-controls="home"     role="tab"
                                data-toggle="tab">Home</a></li>
                            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"
                                data-toggle="tab">Profile</a></li>
                            <li role="presentation"><a href="#messages" aria-controls="messages" role="tab"
                                data-toggle="tab">Messages</a></li>
                            <li role="presentation"><a href="#settings" aria-controls="settings" role="tab"
                                data-toggle="tab">Settings</a></li>
                        </ul>
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">Home</div>
                            <div role="tabpanel" class="tab-pane" id="profile">Profile</div>
                            <div role="tabpanel" class="tab-pane" id="messages">Messages</div>
                            <div role="tabpanel" class="tab-pane" id="settings">Settings</div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <button class="btn btn-default" onclick="javascript:$('#myModal').modal('show');">Click     Me</button>
    </body>
    </html>

**Comment by ialexei** [comment]
Verified. Works like a charm!!!! Thank you !!!!

**Comment by crevete** [comment]
Good catch, why not to make it by default. But still an issue on the ```setRemoveOnHide``` implementation.

**Comment by sjardine** [comment]
Yes.  Much better.  Thanks!

**Comment by crevete** [comment]
See also #335 It's the same issue.

**Comment by sjardine** [comment]
With #400 we reverted the changes made for this issue.  Please use setRemoveOnHide(true) when creating dynamic modals.

If your modal was a singleton then is would not have had this problem.  Since, it is not, you want to remove it from the DOM when it is hidden.

Thanks!

**Comment by srinivasaraomarasu** [comment]
Hi friends,

Is it possible to switch tabs through ajax on click call.Once the modal is open with tabs and one active tab .Now if i click a button inside modal body which should fire a jquery event which switches the active tab and content.what i mean to say is if i click a button in home it will fire a jquery event and active tab should change to messages and corresponding content.
Thanks
