### ISSUE TITLE
DatePicker: HasFormat be consistent with GWT's DateTimeFormat

### ISSUE THREAD

**Issue by manstis** [gwtbootstrap3/gwtbootstrap3#402]
Hi,

I found ```DatePicker.HasFormat``` patterns are inconsistent with GWT's ```DateTimeFormat``` patterns; most particularly (for my use-case at least) ```M```. GWT-BS3 processes ```M``` as "short textual representation of a month, three letters" (e.g. "Jan") whereas GWT would give the numeric month number (e.g. "1"). This is troublesome where I wish to show a ```Date``` in a ```DatePicker``` in some scenarios and (for example) as a ```Label``` in others. 

Is there a utility "mapping" class, to convert GWT's pattern to/from GWT-BS3's pattern; or are there plans to consolidate the patterns (now someone's going to say GWT-BS3's patterns are consistent with BS3 and it's GWT that's the odd one out!!)

Thanks.

Mike

**Comment by sjardine** [comment]
Please move this to gwtbootstrap3-extras.  As far as I know there is not utility mapping class.  Would be happy to see a PR for this!

**Comment by manstis** [comment]
@sjardine Thanks for pointing me to the correct repo!
