### ISSUE TITLE
Did You consider to add to extras TinyMCE plugin?

### ISSUE THREAD

**Issue by masterdany88** [gwtbootstrap3/gwtbootstrap3#403]
Did You consider to add to extras TinyMCE plugin?
I would be great.

**Comment by crevete** [comment]
@masterdany88 

First, you have to create an issue related to extras here :
https://github.com/gwtbootstrap3/gwtbootstrap3-extras

Second, for WYSIWS editors, we have already summernote. Please take a look at :
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#summernote
