### ISSUE TITLE
Button icon positioning problem

### ISSUE THREAD

**Issue by slugmandrew** [gwtbootstrap3/gwtbootstrap3#410]
If a `Button` (any that extends `AbstractIconButton` I believe) is instantiated in UiBinder with no text set, and then has its text set programatically through its `setText()` method, the rendering has a bug. I think it's probably rendering the text in the wrong place which subsequently gives means there is no space between text and icon, and the icon is always on the right.

`<b:AnchorButton ui:field="email" size="SMALL" icon="USER" />` 
`email.setText("test@example.com");`

results in:

![image](https://cloud.githubusercontent.com/assets/153625/10389514/597adcb2-6e6a-11e5-900a-490dff39a2bd.png)

whereas:

`<b:AnchorButton ui:field="email" size="SMALL" icon="USER">text</b:AnchorButton>`
`email.setText("test@example.com");`

results in:

![image](https://cloud.githubusercontent.com/assets/153625/10389568/a6261fc2-6e6a-11e5-950e-a4c4690aa853.png)

I'll try look into it when I have a chance but if anyone else wants to have a look feel free. It might be as simple as calling `render()` again at the end of the `setText()` method of `IconTextMixin`.

**Comment by Grishas** [comment]
I recognize the same issue
In my case work around is not to use icon

On Fri, Oct 9, 2015 at 11:50 AM, Drew Spencer <notifications@github.com>
wrote:

> If a Button (any that extends AbstractIconButton I believe) is
> instantiated in UiBinder with no text set, and then has its text set
> programatically through its setText() method, the rendering has a bug. I
> think it's probably rendering the text in the wrong place which
> subsequently gives means there is no space between text and icon, and the
> icon is always on the right.
>
> <b:AnchorButton ui:field="email" size="SMALL" icon="USER" />
> email.setText("test@example.com");
>
> results in:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/153625/10389514/597adcb2-6e6a-11e5-900a-490dff39a2bd.png>
>
> whereas:
>
> <b:AnchorButton ui:field="email" size="SMALL"
> icon="USER">text</b:AnchorButton>
> email.setText("test@example.com");
>
> results in:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/153625/10389568/a6261fc2-6e6a-11e5-950e-a4c4690aa853.png>
>
> I'll try look into it when I have a chance but if anyone else wants to
> have a look feel free. It might be as simple as calling render() again at
> the end of the setText() method of IconTextMixin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gwtbootstrap3/gwtbootstrap3/issues/410>.
>



-- 
Thanks

**Comment by crevete** [comment]
@slugmandrew @Grishas Do you use the 0.9.1 version ? It seems that it's already been fixed in SNAPSHOT version. Can you get a try and give us a feedback ? Thanks.

**Comment by slugmandrew** [comment]
@crevete I have been using the 1.0-SNAPSHOT for a while and have seen this problem the whole time. As suspected, adding render() after the setText() fixes it. Submitting PR now if there's no reason for this change not to be made

**Comment by slugmandrew** [comment]
see #412

**Comment by crevete** [comment]
Thanks
