### ISSUE TITLE
DropdownMenu doesn't work

### ISSUE THREAD

**Issue by uttam028** [gwtbootstrap3/gwtbootstrap3#414]
DropDownMenu having multiple AnchorListItem (even one) doesn't show items, but I checked click event for anchorbutton works. I have used below code in uibinder file (same as used in demo):
```html
<b:ListDropDown>
	<b:AnchorButton dataToggle="DROPDOWN" ui:field="optionAnchor"></b:AnchorButton>
	<b:DropDownMenu>
		<b:AnchorListItem ui:field="buttonUpdateProfile">Profile</b:AnchorListItem>
	        <b:AnchorListItem ui:field="buttonLogoutAction">Logout</b:AnchorListItem>
	</b:DropDownMenu>
</b:ListDropDown>
 ```

**Comment by sjardine** [comment]
Please provide a sample test case for this problem. I suggest forking the gwtbootstrap3-sample project and modifying it to illustrate the error.

**Comment by uttam028** [comment]
It is working after updating jquery from 1.4.2 to 1.10.0
