### ISSUE TITLE
SuggestBox does not work in a Modal Dialog

### ISSUE THREAD

**Issue by sjardine** [gwtbootstrap3/gwtbootstrap3#431]
See: https://groups.google.com/forum/#!topic/gwtbootstrap3/oh8y_sqQPMg

Quote:
I'm using the version 0.9.1 of gwtbootstrap3, and I just found out that the suggestbox panel is not displayed when placed on a Modal dialog. The reason is the z-index value (default is 1000) of the dropdown-menu. Testing with the value 2000 (over chrome developer tools) makes it works.

**Comment by rjlasko** [comment]
I am also encountering the same issue, using 0.9.1.  Additionally, when changing the z-index of the dropdown list, as stated by Rodrigue, i still cannot mouse-select any items in that menu.  So, this particular combination appears to be broken, unless we are using it incorrectly.

**Comment by sjardine** [comment]
Would you be interested in submitting a PR for this issue?

**Comment by sjardine** [comment]
Should be fixed.
