### ISSUE TITLE
ListBox could implement HasValue<String>

### ISSUE THREAD

**Issue by pefernan** [gwtbootstrap3/gwtbootstrap3#434]
I'm working on a project using Errai Binding and I found that ```ListBox``` weren't working. After digging a bit on the code I found that ```ListBox``` isn't implementing ```HasValue<String>```, which surprised me a lot. 

As a workaround on my project I created a custom ```ListBox``` widget that implements ```HasValue<String>```. 

I have already forked the gwtbootstrap3 project and if you want I can fix it and do a PR with the required changes.

**Comment by sjardine** [comment]
I think ValueListBox is the widget your looking for.

**Comment by pefernan** [comment]
Thank you very much, I wasn't aware of that widget.
