### ISSUE TITLE
Datagrid

### ISSUE THREAD

**Issue by fabm** [gwtbootstrap3/gwtbootstrap3#436]
I'm using the version 0.91 of gwtbootstrap3, I try to add a datagrid, in my page but with success, I realise the grid is there, but is with position absolute, within a relative panel.

**Comment by sjardine** [comment]
Please fork https://github.com/gwtbootstrap3/gwtbootstrap3-seed and provide a complete example illustrating the problem.  We need a lot more information in order to troubleshoot.

**Comment by fabm** [comment]
I'm sorry Steven, my bad, in fact a did it the wrong way.
