### ISSUE TITLE
DateTimePicker returns wrong time when in 24-hour mode

### ISSUE THREAD

**Issue by FrankW76** [gwtbootstrap3/gwtbootstrap3#440]
When using a 24-hour DateTimePicker, the onChangeDate event always returns an hour in the morning. If you for example select 23:00, you will get a Date object with 11:00.

This reproducable in the demo-website.
If you go to https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker and you select an hour in the afternoon in the first demo, you will see the textbox updating to the same hour in the morning.

**Comment by sjardine** [comment]
Thanks for reporting this issue.  Would you please open an issue in the gwtbootstrap3-extras project?
