### ISSUE TITLE
DateTimePicker returns wrong time when in 12-hour mode

### ISSUE THREAD

**Issue by FrankW76** [gwtbootstrap3/gwtbootstrap3#441]
When using a 12-hour DateTimePicker, the textbox gets updated to not-existing times.

This reproducable in the demo-website.
If you go to https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker and you select an PM hour the textbox will update to 24 hour format with PM appended... For example : 11/25/2015 23:00 PM. 23:00 PM is a non-existing thing :-)

**Comment by sjardine** [comment]
Thanks for reporting this issue.  Would you please open an issue in the gwtbootstrap3-extras project?
