### ISSUE TITLE
Update summernote JS plugin to v0.7.0

### ISSUE THREAD

**Issue by josue270193** [gwtbootstrap3/gwtbootstrap3#446]
I would like to see if you can implement the new version of summernote to v0.7.0, mainly for the new feature Hint (autocomplete). Thanks

**Comment by crevete** [comment]
This library should be reworked ; If you could make a PR, that would be great. Anyway, please create a new issue in https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues. Thanks

**Comment by crevete** [comment]
@josue270193 FYI, I'm working on summernote 0.7.0 and will make a PR for this with Hint, airMode, placeholder, etc.
