### ISSUE TITLE
Fullcalendar - Background Events

### ISSUE THREAD

**Issue by MittiMartin** [gwtbootstrap3/gwtbootstrap3#452]
In your example for background events, you can give an whole day a specific color.
![image](https://cloud.githubusercontent.com/assets/15977182/12117477/478f4fd2-b3c1-11e5-9227-888a822df487.png)

Therefore you used the method setRendering and setOverlap but these methods doesn't exist.
![image](https://cloud.githubusercontent.com/assets/15977182/12117556/d9f8b156-b3c1-11e5-8b36-4ab3b1c1a5ac.png)

I can only give an event an specific color.
![image](https://cloud.githubusercontent.com/assets/15977182/12117626/55cd357c-b3c2-11e5-97ed-8891ec165e5e.png)

Can you help me?

**Comment by crevete** [comment]
First, this issue should be created https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues.

Second, I'm not sure I understand your question, but these methods do exist: 
```org.gwtbootstrap3.extras.fullcalendar.client.ui.Event.setRendering(String)```
```org.gwtbootstrap3.extras.fullcalendar.client.ui.Event.setOverlap(boolean)```
