### ISSUE TITLE
Image gallery controls not showing

### ISSUE THREAD

**Issue by clintonbosch** [gwtbootstrap3/gwtbootstrap3#453]
It seems as though there might be an issue with showing the controls (prev button, next button, close button and indicator). I have tried setting them as follows 

        gallery.setShowCloseButton(true);
        gallery.setShowIndicator(true);
        gallery.setShowNextButton(true);
        gallery.setShowPrevButton(true);

But I can not see any controls when viewing the lightbox

**Comment by sjardine** [comment]
Please file this with the gwtbootstrap3-extras project.  Thanks!

**Comment by crevete** [comment]
@clintonbosch The controls are hidden by default; you just have to click on an image to make them visible. The orignal author did not do it well, many functionalities are not supported, any many things are hard-coded, etc. A review is needed, but it takes a lot of times...
