### ISSUE TITLE
DatePicker doesn't work with setFormat("dd/mmmm/yyyy");

### ISSUE THREAD

**Issue by davepuppets** [gwtbootstrap3/gwtbootstrap3#457]
My code look like something like this:
`DatePicker datePicker = new DatePicker();`
`datePicker.setFormat("dd/mmmm/yyyy");`

And then, when I try to pick up a date with the visual element, 
I get this: 

> 02/022/2016

 instead of 

> 02/February/2016

We get a similar problem with `datePicker.setFormat("dd/mmm/yyyy");`

**Comment by crevete** [comment]
@davepuppets Can you please create an issue in the extra project :

https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues

Thank you!
