### ISSUE TITLE
0.9.3 release

### ISSUE THREAD

**Issue by crevete** [gwtbootstrap3/gwtbootstrap3#458]
@sjardine I think it's time to cut a 0.9.3 release after massive changes in the extra project. Also we could get more feedbacks. What's your opinion?

**Comment by sjardine** [comment]
Absolutely.  I will start working on a release.

**Comment by sjardine** [comment]
I will probably wait a couple of days just to make sure there aren't any lingering changes.  Does that sound ok?

**Comment by crevete** [comment]
Yep you are right :+1:

**Comment by sjardine** [comment]
It seems like we are ready to tag the 0.9.3 release.  @crevete, do you agree?

**Comment by sjardine** [comment]
Here is the proposed changelog, please let me know if you have any additions:

**Change Log**

* Updated bootstrap to 3.3.6
	* Removed bootstrap css source mapping reference to prevent "404 NOT FOUND" issue when loading bootstrap resources.
* Updated font-awesome to 4.5.0
* Updated jquery to 1.12.0

* Refactored both Tooltip and Popover to use AbstractTooltip which contains common code for both.
	* Changes to Tooltip and Popover are now made immediately without the need to call reconfigure.
* Badges implemented for Buttons, Tabs, Navs, and AnchorListItem
* Fixed bug with SuggestBox not setting z-index correctly.
* Fixed bug with ListItem not setting text properly.
* Added HasReadOnly interface for ValueBoxBase.
* Improved JavaDoc.

Other various bug fixes and improvements.

**Comment by sjardine** [comment]
Changelog for **gwtbootstrap-extras** , please let me know if you have any additions:

** Change Log **

* Updated Animate CSS to 3.5.1
* Updated datepicker resources to 1.5.1 Added missing supported languages
* Updated gallery to 3.3.6
* Updated slider to 6.0.17
* Updated summernote to 0.8.1
	* Complete rewrite of summernote functionality.
	* Added new features: hint, air-mode, placeholder, etc.
	* Font Awesome icons are removed.
	* Added font name customization API.
	* Added new dialog API.
	* Added new toolbar buttons.
* Updated DateTimePicker to 2.3.8
	* Renamed DateTimePicker css and js files
	* Added setGWTFormat(String format) method to DateTimePickerBase
	* Changed default format to use 24 hour format
	* Fixed 203, 242 - Date popup does not hide after manually changing date.
* Updated select to 1.10.0
	* Complete rewrite of select functionality.
	* Fixes issues 53, 57, 112, 266
* Implemented setVisible and isVisible methods for ToggleSwitch.
* Updated bootbox to 4.4.0.
	* Added missing APIs for full support.
* Added missing APIs to bootbox 4.4.0.
* Added access for some ".map.js" files to prevent "404 NOT FOUND" issue when loading JS files
* Typeahead now is initialized with a default empty dataset.
* ToggleSwitch now implements HasReadOnly interface
* Improved JavaDoc.

Other various bug fixes and improvements.

**Comment by crevete** [comment]
@sjardine Awesome work :-)

**Comment by sjardine** [comment]
OK. Done!

**Comment by crevete** [comment]
Thanks :+1:

**Comment by slugmandrew** [comment]
Thanks for all your great work guys. I'll make sure to add some examples to the showcase for the tabs with badges and icons. Sorry, that kinda slipped my mind around Christmas time! :santa:
