### ISSUE TITLE
AnchorButton caret render problem

### ISSUE THREAD

**Issue by vortekc** [gwtbootstrap3/gwtbootstrap3#477]
Buttons with caret and icon will show caret in the wrong place.
For example we have some AnchorButton.
anchorButton.setText("Some text");
anchorButton.setIconPosition(IconPosition.LEFT);
anchorButton.setToggleCaret(true);

And we got not right elements positions: "Icon Caret Some text" instead of "Icon Some text Caret"

Seems problem is in IconTextMixin.java render function.

**Comment by v00d00** [comment]
Seeing that here too.

**Comment by crevete** [comment]
I didn't reproduced it yet, but it seems a real bug.

**Comment by nemoo2580** [comment]
There is a problem with Text widget and ComplexPanel insert method:

![widgetinsertbug](https://cloud.githubusercontent.com/assets/11309611/17379653/aa485bd4-59c3-11e6-86aa-e16fad3c64a5.png)
Logical attach is ok, but physical not.

ComplexPanel insert method is used in IconTextMixin which has icon and badge separator as Text widget. This causes an incorrect widgets position.

A workaround is replace separator Text widget with Span widget and small fix in IconTextMixin render method. I can do MR, if it's a good solution.

**Comment by crevete** [comment]
The real problem is in the ```ComplexePanel.insert()``` method:
```
// Physical attach.
if (domInsert) {
  // When child.getElement() is a text node, it always append it at the last position
  DOM.insertChild(container, child.getElement(), beforeIndex);
} else {
  DOM.appendChild(container, child.getElement());
}
```
GWT handles differently ```com.google.gwt.dom.client.Element``` and ```com.google.gwt.dom.client.Text```, but the original author of GWTBootstrap3 created the widget ```org.gwtbootstrap3.client.ui.html.Text``` which casts the ```Text``` to ```Element```. So when calling basic GWT APIs to manipulating DOM, it causes some side effects like this issue.
Please also see my comments in #486.
