### ISSUE TITLE
Anchor widget cannot be updated (setText, setIconType, etc. fails)

### ISSUE THREAD

**Issue by trohr** [gwtbootstrap3/gwtbootstrap3#486]
There is a bug in the Anchor widget that throws an exception if any of the fields are updated using setters after the UiBinder initially set the values.
This is true in Mozilla Firefox and MS Edge browsers.

The failure occurs in the IconTextMixin render method in calling 'removeFromParent' on the 'text' element.

In firefox this error manifests itself with this error message in the console: `TypeError: this$static_0_g$ is null`
In Edge, there is more detail: `TypeError: Unable to get property 'removeChild' of undefined or null reference`

I have fiddled with the render method in my checkout of gwtbootstrap3 source code: the issue is not linked to drawing before the parent widget (Anchor) has been attached, etc. It occurs every time I try to update the Anchor widget.
This issue does not impact the Button widget.

I have included a small example:
[BootstrapTestView.zip](https://github.com/gwtbootstrap3/gwtbootstrap3/files/428389/BootstrapTestView.zip)

**Comment by trohr** [comment]
After two days of searching for the problem, I have finally found the underlying issue.

## Problem is
1. I used this ui binder code to create the anchor:
`<b:Anchor>Anchor text</b:Anchor>`
Not the way you specified in the docs:
`<b:Anchor text="Anchor text" />`

2. Because your `Anchor` widget implements the `HasHTML` interface, the text has been passed by UiBinder to the `setHTML(String)` method instead of the expected `setText(String)` method and the contents created by the `IconTextMixin` have been overwritten.

## Solution
I personally think that the `Anchor` widget should not implement `HasHTML` because all of the other methods of the widget suppose its contents are managed inside it (using the `IconTextMixin`) as a black box.

But there may be some production systems that use the 'feature'.

What will be your solution of the problem?

**Comment by crevete** [comment]
@trohr Thanks for the real bug. I have reproduced this bug in Firefox, but not in Chrome (Edge not tried yet). The ```Anchor``` should implements ```HasHTML``` widget because in gwtbootstrap3, we may have something like this:
```
<a>
  <span style="fa fa-check"></span>
  Some text
</a>
```

The real issue is the ```Text``` widget:
```
private final com.google.gwt.dom.client.Text text;
public Text(final String txt) {
    // The text here is a text node
    text = Document.get().createTextNode(txt);
    // But we cast it to private final com.google.gwt.dom.client.Element
    setElement(text.<Element>cast());
}
```
In GWT:
com.google.gwt.dom.client.Node
|--> com.google.gwt.dom.client.Element
|--> com.google.gwt.dom.client.Text

According to this hierarchy, ```Text``` cannot be casted to ```Element```, but the original author of GWTBootstrap3 did... That's why when a text node is detaching from DOM, when calling ```ComplexPanel.remove(Widget)```, ```DOM.getParent(elem).removeChild(elem);``` throws a NPE because ```DOM.getParent(elem)``` returns null (here the ```elem``` is the text node casted to ```Element```). So temporarily, the best fix would be overriding ```ComplexPanel.remove(Widget)``` in ```org.gwtbootstrap3.client.ui.base.ComplexWidget``` by replacing ```DOM.getParent(elem).removeChild(elem);``` by ```elem.removeFromParent()``` which does the same job but never fails.

**Comment by trohr** [comment]
I can confirm your changes fix the issue in both Firefox and MS Edge.

Still, using `<b:Anchor>Anchor text</b:Anchor>` and `anchor.setText(...)` is somewhat funny as the text managed by IconTextMixin gets appended to the HTML contents.

I would expect the Anchor code to work either with HTML contents (managed independently) OR with IconTextMixin -- not both at the same time. (IMHO setHTML(String) should disable the IconTextMixin functionality and vice versa). This is however out of scope of this error report.

Thank you very much.

FYI: I have a lot of small changes in the gwtbootstrap3 library in my local copy. I will try to make it public on github and make some pull requests. Since then, bye.

Tomas

**Comment by crevete** [comment]
@trohr I'm agree with you to separate setHTML(String) and IconTextMixin for Anchor widget. We may probably create a new widget for this. Feel free to share your improvement by making some PR, please just comment your changes or create an issue before, thank you!
