### ISSUE TITLE
Pagination on Simple/Multiple Select

### ISSUE THREAD

**Issue by sauldeleon** [gwtbootstrap3/gwtbootstrap3#489]
Hi!

It would be great to have pagination(if it is possible) inside a multiple select.

In my case, I'm using a multiple select where a user is able to select multiple actions to asign it for a specific role, and there are more than 100 actions.

We have added the live search and the limit to show the scroll, but I have thought that a pagination in the dropdownlist and show 10 by 10 actions or something similar would be great, or maybe some aproach?

Thanks!

Regards,

Saúl

**Comment by crevete** [comment]
This request seems out of the scope of gwtbootstrap3-extras which is supposed to be just a "wrapper" of external widget. I would suggest you to create an issue in the Bootstrap select project for this feature. Thanks

**Comment by sauldeleon** [comment]
@crevete ok! thanks!
