### ISSUE TITLE
how to get theme ? 

### ISSUE THREAD

**Issue by Neo110** [gwtbootstrap3/gwtbootstrap3#493]
from 
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#setup

1. For the setup with a custom theme inherit the GwtBootstrap3 your *.gwt.xml. 
2. Next, download the theme that you wish to use. 
3. Then, place the CSS/JS files from the theme either in your public folder or a resource folder. 
4. If you use a resource folder, link the resource folder as public path in your *.gwt.xml. 
5. Link the CSS/JS files into your *.gwt.xml AFTER the GwtBootstrap3 inherit. 

how to get this about files?

**Comment by crevete** [comment]
What "files" are you talking about ? Bootstrap theme CSS files ?
