### ISSUE TITLE
GwtBootstrap Extra - ToggleSwitch();

### ISSUE THREAD

**Issue by platform2** [gwtbootstrap3/gwtbootstrap3#496]
I use GwtBootstrap Extra 0.9.3 in my application. I have some following code:

ToggleSwitch toggleSwitch = new ToggleSwitch();
FlowPanel  flowPanel = new FlowPanel();
flowPanel.add(toggleSwitch);

return flowPanel;

Once I run in Chrome, I got the following exception:

Throwable.java:121 Uncaught Error: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : $wnd.jQuery is not a function(…)

I confirmed Window.jQuery is not defined in Chrome development tool. But on http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#toggleswitch, Window.jQuery is defined. I don't know why jQuery is not loaded on my application. Please help me out.

James

**Comment by crevete** [comment]
Did you import directly or indirectly the GWT module
```<inherits name="org.gwtbootstrap3.client.Resources"/>``` BEFORE toggleSwitch resources? If not, you have to ensure your self that jQuery.js is injected.

**Comment by crevete** [comment]
Next time, please create an issue in the extras project. Thanks!

**Comment by platform2** [comment]
Thanks for your reply.

After I added <inherits name="org.gwtbootstrap3.client.Resources"/>. I got
another error -  $wnd.jQuery(...).bootstrapSwitch is not a function(…).

Now my gwt.xml looks like the following:

<inherits name="org.gwtbootstrap3.client.Resources"/>

    <inherits name="org.gwtbootstrap3.GwtBootstrap3"/>

    <inherits name="org.gwtbootstrap3.extras.toggleswitch.ToggleSwitch"/>


James
