### ISSUE TITLE
GwtBootstrap Extra - ToggleSwitch();

### ISSUE THREAD

**Issue by platform2** [gwtbootstrap3/gwtbootstrap3#497]
I use GwtBootstrap Extra 0.9.3 in my application. I have some following code:

ToggleSwitch toggleSwitch = new ToggleSwitch();
FlowPanel  flowPanel = new FlowPanel();
flowPanel.add(toggleSwitch);

Once I run in Chrome, I got the following exception:

Throwable.java:121 Uncaught Error: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : $wnd.jQuery is not a function(…)

I confirmed Window.jQuery is not defined in Chrome development tool. But on http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#toggleswitch, Window.jQuery is defined. I don't know why jQuery is not loaded on my application. Please help me out.

James

**Comment by crevete** [comment]
@platform2 I've responded in #496. Please an create issue in [extras project](/gwtbootstrap3/gwtbootstrap3-extras/issues). Thanks!

**Comment by platform2** [comment]
I just did it.

Thanks,

Jamas
