### ISSUE TITLE
Ownership of gwtbootstrap3.org

### ISSUE THREAD

**Issue by svenjacobs** [gwtbootstrap3/gwtbootstrap3#501]
About four years ago I started GwtBootstrap3. At that time I was an IT consultant. As part of a Java/Web project I created this library since I was not satisfied with the available frameworks back then which were based on Bootstrap 3. Since more than two years I'm now an Android developer and have no personal need for Bootstrap nor time to maintain this project.

However I'm still the owner of the domain [gwtbootstrap3.org](http://gwtbootstrap3.org). Is any of the current maintainers interested in adopting the domain @crevete @sjardine @jgodi? The domain has been paid till 16th December 2017 so there's no rush. However I will not renew the domain by end of this year.

**Comment by svenjacobs** [comment]
Just a reminder that the domain expires by end of the year @crevete @sjardine @jgodi.

**Comment by jgodi** [comment]
I too am no longer using GWT and haven't been for awhile. @sjardine has basically been maintaining this project. Thanks for the heads up!

**Comment by svenjacobs** [comment]
Happy New Year!
The domain has not been renewed so I'm closing this issue.
