### ISSUE TITLE
Version 0.9.4 breaks IE8 compatibility due regression bug

### ISSUE THREAD

**Issue by rflamia** [gwtbootstrap3/gwtbootstrap3#505]
My application was developed with 0.9.3 version and I'm constrained to support IE8; now, updating to 0.9.4, there's the same bug noticed at bug #137; the cause is the fix for the bug #486.

**Comment by sjardine** [comment]
I am inclined not to try and chase down IE8 problems. It's been over a year since Microsoft has stopped supporting IE8 and support for IE8 and IE9 are pretty much being universally dropped by all.  @crevete Do you have any opinion on this?

@rflamia I would recommend not upgrading to 0.9.4.

**Comment by sjardine** [comment]
@rflamia I would be willing to look at a PR for this issue if you were inclined to provide one.

**Comment by rflamia** [comment]
Thank you for suggestion, I've already rollback to 0.9.3, unfortunately the compatibility with IE8 can not be avoided ... :-(. 

This are my 2 cents: the gwtbootstrap3 project was developed with IE8 compatibility in mind, and Bootstrap 3 is IE8 friendly with Respond module. If we want to continue this way, maybe we can provide 2 distinct implementations for Text and ComplexWidget (one for IE8, the other for others browsers) and let gwt deferred binding do his job, so both issues will be resolved (if I've understood correctly the problems). 

In next days I'll evaluate my effort for PR, I'm actually very busy at work.

**Comment by sjardine** [comment]
@rflamia I completely understand your viewpoint.  I don't have time to chase IE8 issues so the only way this gets fixed is by PR.  I'll leave this issue open for the time being just in case @crevete or someone else would like to work on it.
