### ISSUE TITLE
Container setFluid(false) has no effect

### ISSUE THREAD

**Issue by sebastian-raubach** [gwtbootstrap3/gwtbootstrap3#509]
Looking at the source of `Container#setFluid(boolean)`, I realized that calling it with false doesn't have any effect.

This could easily be solved by changing the code to this:

	@Override
	public void setFluid(boolean isFluid)
	{
		if (isFluid)
		{
			removeStyleName(Styles.CONTAINER);
			addStyleName(Styles.CONTAINER_FLUID);
		}
		else
		{
			removeStyleName(Styles.CONTAINER_FLUID);
			addStyleName(Styles.CONTAINER);
		}
	}

If the `boolean` parameter doesn't have an effect in both cases, then why have it in the first place? 
I'm currently subclassing `Container` to achieve this.

**Comment by sjardine** [comment]
Are you changing the style of the container at runtime?

**Comment by sebastian-raubach** [comment]
Yes, I am calling it at runtime. Why has this been closed before I had a chance to reply?

**Comment by sjardine** [comment]
Sorry for the confusion.  Fixed with PR #510.  The reason I was asking is that I am having difficulty grasping the use case for adding and removing the fluid attribute at runtime.  Usually, you would have a container that is either fluid or not and the attribute doesn't need to be changed.
