### ISSUE TITLE
Dropdown button menu in celltable header for filtering

### ISSUE THREAD

**Issue by cRUSHER-HLG** [gwtbootstrap3/gwtbootstrap3#519]
Hello guys, 
I want to ask if someone can say/help me to tell me how do i need to implement a dropdown menu button into the celltable header. The dropdown menu button will contain a textbox who you can search and at the bottom the filtering option for the given column. With uibinder it dont works for me so i need todo it programmaticaly.
I hope that you can give me a answer how i need todo it or give me a way how do i need to implement it. 
Good Regards,
cRUSHER

**Comment by sjardine** [comment]
Please use the mailing list for questions about implementation.
