### ISSUE TITLE
bootstrap-3.4.0 is vulnerable

### ISSUE THREAD

**Issue by fertkir** [gwtbootstrap3/gwtbootstrap3#520]
bootstrap-3.4.0 is vulnerable. Please see the following:
https://github.com/twbs/bootstrap/issues/20184
https://github.com/twbs/bootstrap/issues/25679

Please update bootstrap-3.3.7.min.cache.js to version 3.4

**Comment by arikanorh** [comment]
Yes, we got a vulnerability issue on a penetration test. We need to fix this asap

**Comment by thiagoricciardi** [comment]
I'm going to update the bootstrap version and create a pull request.

**Comment by fertkir** [comment]
Cool, thanks!

**Comment by sjardine** [comment]
Fixed with #521.  Please test and I will create a release.

**Comment by bbrudnoy** [comment]
It doesn't seem like either a release or an update of 1.0-SNAPSHOT on Maven Central has happened after #521 was merged. Is local build my only option?
