### ISSUE TITLE
Automatically deploy snapshot releases to Sonatype Nexus from BuildHive

### ISSUE THREAD

**Issue by svenjacobs** [gwtbootstrap3/gwtbootstrap3#92]
Need to find a solution because this doesn't seem to be possible at the moment without making Nexus credentials publicly visible, see [here](https://cloudbees.zendesk.com/entries/21607711-BuildHive-Private-WebDAV-for-Maven-repository-credential-settings-xml-etc-).

**Comment by ArloL** [comment]
@jgodi This can be closed now with the new Travis CI build.

**Comment by jgodi** [comment]
Thank you for combing through the issues.
